import React from "react"
import Lock from "assets/svg/ic_lock.svg"
import Email from "assets/svg/ic_email.svg"
export default {
    avatar:require("assets/images/avatar.png"),
    bgLogin:require("assets/images/bg_login.jpeg"),
    bgSignup:require("assets/images/bg_signup.jpeg"),
    bgWallet:require("../../assets/images/bg_wallet.png"),
    copy:require("../../assets/icons/ic_copy.png"),
    ggAuthenL: require("../../assets/images/gg_authen_l.png"),
    ggAuthenL2: require("../../assets/images/gg_authen2_l.png"),
    logo: require("assets/svg/Logo.svg"),
    bg: require("../../assets/images/bg.jpg"),
    swap: require("../../assets/icons/swap_ic.png"),
    swap_right: require("../../assets/icons/swap_right.png"),
    logoBlue: require("../../assets/images/logo_blue.png"),
    logoXwallet: require("../../assets/images/logo_xwallet.png"),
    bgTopbar: require("../../assets/images/title_icon.png"),
    textXwalet: require("../../assets/icons/XWallet.png"),
    changePass: require("../../assets/icons/ic_change_pass.png"),
    passCode: require("../../assets/icons/ic_passcode.png"),
    about: require("../../assets/icons/ic_about.png"),
    currency: require("../../assets/icons/ic_currency.png"),
    language: require("../../assets/icons/ic_language.png"),
    support: require("../../assets/icons/ic_support.png"),
    sercurity: require("../../assets/icons/ic_sercurity.png"),
    telegram: require("../../assets/icons/ic_telegram.png"),
    twitter: require("../../assets/icons/ic_twitter.png"),
    gmail: require("../../assets/icons/ic_gmail.png"),
    medium: require("../../assets/icons/ic_medium.png"),
    fb: require("../../assets/icons/ic_fb.png"),
    gg2fa: <Lock />,
    email2fa: <Email/>,
    withdraw: require("../../assets/icons/ic_withdraw.png"),
    deposit: require("../../assets/icons/ic_deposit.png"),
    emailSupport: require("../../assets/icons/icon_support1.png"),
    teleSupport: require("../../assets/icons/icon_support2.png"),
    fbSupport: require("../../assets/icons/icon_support3.png"),
}