platform :ios, '9.0'

use_frameworks!

target 'FinanceX' do
    pod 'SwiftyJSON', '4.0.0'
    pod 'Charts', '3.1.1'
#    pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/'
#    pod 'React', path: '../node_modules/react-native/', :subspecs => [
#    'Core',
#    'ART',
#    'RCTActionSheet',
#    'RCTAnimation',
#    'RCTLinkingIOS',
#    'RCTGeolocation',
#    'RCTImage',
#    'RCTNetwork',
#    'RCTText',
#    'RCTVibration',
#    'RCTWebSocket',
#    'DevSupport',
#    'CxxBridge',
#    ]
#
#    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#
#    pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'


  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'


  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'




  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'



  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end

swift4 = ['Charts']

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
